apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends-web
    tag: techtrends-web
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: techtrends-web
    tag: techtrends-web
  type: {{ .Values.service.type }} 
