namespace:
  name: staging 
 
service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: ardhian09/techtrends
  tag: v1.0.0
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 90m
    memory: 300Mi
  limits:
    cpu: 128m
    memory: 500Mi
    
ports: 
    - containerPort: 3111
      protocol: TCP
  
livenessProbe:
    httpGet:
        path: /healthz
        port: 3111
    initialDelaySeconds: 3
    periodSeconds: 3
readinessProbe:
    httpGet:
        path: /healthz
        port: 3111
    initialDelaySeconds: 3
    periodSeconds: 3
    


