namespace:
  name: prod
 
service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: ardhian09/techtrends:v1.0.0
  tag: techtrends
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 128m
    memory: 350Mi
  limits:
    cpu: 256m
    memory: 500Mi
    
ports: 
    - containerPort: 3111
      protocol: TCP
  
livenessProbe:
    httpGet:
        path: /healthz
        port: 3111
    initialDelaySeconds: 3
    periodSeconds: 3
readinessProbe:
    httpGet:
        path: /healthz
        port: 3111
    initialDelaySeconds: 3
    periodSeconds: 3
    


