name: techtrends-prod

namespace:
  name: prod
 
service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: ardhian09/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
    
ports: 
    - containerPort: 3111
      protocol: TCP
  
livenessProbe:
    httpGet:
        path: /healthz
        port: 3111
    initialDelaySeconds: 3
    periodSeconds: 3
readinessProbe:
    httpGet:
        path: /healthz
        port: 3111
    initialDelaySeconds: 3
    periodSeconds: 3
    


